# Jellyfin Media Server for Windows Container

# Author:     Cameron Kollwitz <cameron@kollwitz.us>
# Created:    2020/09/04 (YYYY/MM/DD)
# Updated:    2020/09/05 (YYYY/MM/DD)
# Notes:      NaH

version: "3.7"

########################### NETWORKS
networks:
  # Stack-Only Networking
  internal:
    driver: overlay
    attachable: true
  # External Networking
  # All front-facing external services attach to this network!
  external:
    external: true

########################### SECRETS
#secrets:
#  secret_name_here:
#    external: true

########################### VOLUMES
#volumes:
#  media: # NFS Volume Mount!
#    external: true

########################### SERVICES
services:
# All services / apps go below this line!

  # Jellyfin Media Server for Windows Containers
  jellyfin-windows:
    image: cameronkollwitz/jellyfin-windows:10.6.4
    deploy:
      placement:
        # Restrict placement of the service to Windows nodes only
        constraints: [node.platform.os == windows]
      restart_policy:
        condition: any
    environment:
      JELLYFIN_PublishedServerUrl: "http://jellyfin.${DOMAIN}"
      TZ: "America/Los_Angeles"
    networks:
      internal:
      external:
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
      - target: 8920
        published: 8920
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
      - target: 7359
        published: 7359
        protocol: udp
    volumes:
      - type: volume
        source: AppData
        target: C:\Jellyfin\AppData
      - type: volume
        source: Scripts
        target: C:\Scripts
      - type: volume
        source: Temp
        target: C:\Temp
      #- type: volume
      #  source: Media
      #  target: C:\Media
