# Jellyfin Media Server for Windows Container

# Author:     Cameron Kollwitz <cameron@kollwitz.us>
# Created:    2020/09/04 (YYYY/MM/DD)
# Updated:    2020/09/04 (YYYY/MM/DD)
# Notes:

version: "3.7"

########################### NETWORKS
networks:
  # Stack-Only Networking
  internal:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.32.176.0/24
  # External Networking
  # All front-facing external services attach to this network!
  traefik_public:
    external: true

########################### SECRETS
#secrets:
#  secret_name_here:
#    external: true

########################### VOLUMES
volumes:
  AppData:
    external: true
  AppData_TEST:
    external: true
  Media:
    external: true
  Scripts:
    external: true
  Temp:
    external: true

########################### SERVICES
services:
# All services / apps go below this line!

  # Jellyfin Media Server for Windows Containers
  jellyfin-windows:
    image: cameronkollwitz/jellyfin-windows:unstable
    deploy:
      labels:
        traefik.enable: "false"
        traefik.docker.network: "traefik_public"
        ## HTTP Routers
        traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
        traefik.http.routers.jellyfin-rtr.rule: "Host(`jellyfinwindows.kollwitz.cloud`)"
        ## HTTPS Services
        traefik.http.routers.jellyfin-rtr.entrypoints: "https"
        traefik.http.routers.jellyfin-rtr.tls.certresolver: "dns-cloudflare"
        # SSL Certificates
        traefik.http.routers.jellyfin-rtr.tls.domains[0].main: "*.kollwitz.cloud"
        traefik.http.routers.jellyfin-rtr.tls.domains[0].sans: "kollwitz.cloud"
        #traefik.http.routers.jellyfin-rtr.tls.domains[1].main: "*.DOMAIN2.TLD"
        #traefik.http.routers.jellyfin-rtr.tls.domains[1].sans: "DOMAIN2.TLD"
        ## HSTS Header Middleware
        traefik.http.middlewares.jellyfin.headers.SSLRedirect: "true"
        traefik.http.middlewares.jellyfin.headers.STSSeconds: "315360000"
        traefik.http.middlewares.jellyfin.headers.browserXSSFilter: "true"
        traefik.http.middlewares.jellyfin.headers.contentTypeNosniff: "true"
        traefik.http.middlewares.jellyfin.headers.forceSTSHeader: "true"
        traefik.http.middlewares.jellyfin.headers.SSLHost: ""
        traefik.http.middlewares.jellyfin.headers.STSIncludeSubdomains: "true"
        traefik.http.middlewares.jellyfin.headers.STSPreload: "true"
        traefik.http.middlewares.jellyfin.headers.frameDeny: "true"
        ## Middleware Chains
        #traefik.http.routers.jellyfin-rtr.middlewares: "chain-authelia@file" # Authelia
        #traefik.http.routers.jellyfin-rtr.middlewares: "chain-basic-auth@file" # .htpasswd Authentication
        traefik.http.routers.jellyfin-rtr.middlewares: "chain-no-auth@file" # No Authentication
        #traefik.http.routers.jellyfin-rtr.middlewares: "chain-oauth@file" # Traefik-Forward-Auth
      placement:
        # Restrict placement of the service to Windows nodes only
        constraints: [node.platform.os == windows]
      restart_policy:
        condition: any
    environment:
      TZ: "America/Los_Angeles"
    networks:
      internal:
      traefik_public:
    ports:
      - target: 8096
        published: 38096
        protocol: tcp
    volumes:
      - type: volume
        source: AppData_TEST
        target: C:\Jellyfin\AppData
      - type: volume
        source: AppData
        target: C:\Users\ContainerAdministrator\AppData\Local\jellyfin
      - type: volume
        source: Media
        target: C:\Media
      - type: volume
        source: Scripts
        target: C:\Scripts
      - type: volume
        source: Temp
        target: C:\Temp
